services:
  adonis:
    build:
      context: .
      dockerfile: ${DOCKERFILE:-Dockerfile.prod}
      target: ${TARGET:-prod}
    container_name: yayasan-fokus-app
    env_file:
      - path: ${ENV_FILE:-.env}
    ports:
      - '3333:3333'
    volumes:
      # Mount database directory where SQLite file is actually stored
      - sqlite_data:/database
      # Mount logs directory to access cron logs
      - logs_data:/var/log
      # Optional: Mount git directory if you want to preserve git history
      # - ./.git:/app/.git:ro
    networks:
      - app-network
    restart: unless-stopped
    # Keep container running even if main process exits
    tty: true
    stdin_open: true

networks:
  app-network:
    driver: bridge

volumes:
  sqlite_data:
  logs_data:
